//go:build unix

package service

import (
	"context"
	"errors"
	"fmt"
	"os"
	"runtime"
	"strconv"
	"syscall"
	"time"

	"github.com/yourchocomate/hampp/internal/proc"
)

// CodeServer runs VS Code in the browser (code-server from TUR) on ~/www.
type CodeServer struct{}

func (CodeServer) Name() string       { return "code" }
func (CodeServer) Title() string      { return "code-server" }
func (CodeServer) Packages() []string { return []string{"code-server"} }
func (CodeServer) Configure(*Ctx) error {
	return nil
}

// ErrUnsupportedArch is returned on i686, which TUR does not build code-server for.
var ErrUnsupportedArch = errors.New("code-server is not packaged for i686 (x86) devices")

func (s CodeServer) Start(ctx context.Context, c *Ctx) error {
	if runtime.GOARCH == "386" {
		return ErrUnsupportedArch
	}
	pidFile := run(c, "code-server.pid")
	if proc.Running(pidFile) > 0 {
		return nil
	}
	if err := checkPort("127.0.0.1", c.Cfg.Code.Port, "code-server"); err != nil {
		return err
	}
	addr := "127.0.0.1:" + strconv.Itoa(c.Cfg.Code.Port)
	args := []string{
		"--bind-addr", addr,
		"--auth", "password",
		"--user-data-dir", c.Paths.CodeServerData(),
		"--config", conf(c, "code-server.yaml"),
		"--disable-telemetry",
		"--disable-update-check",
		c.Cfg.Web.Root,
	}
	if err := os.WriteFile(conf(c, "code-server.yaml"), []byte("# Generated by hampp; the password comes from $PASSWORD.\nauth: password\ncert: false\n"), 0o600); err != nil {
		return err
	}
	// code-server only reads the password from $PASSWORD or its config file.
	env := []string{"PASSWORD=" + c.Creds.CodePassword}
	if _, err := proc.Spawn(c.Env.Bin("code-server"), args, env, logf(c, "code-server.log"), pidFile); err != nil {
		return err
	}
	wctx, cancel := waitCtx(ctx, 60*time.Second)
	defer cancel()
	if err := proc.WaitDial(wctx, "tcp", addr); err != nil {
		return failure(err, logf(c, "code-server.log"))
	}
	return nil
}

func (s CodeServer) Stop(_ context.Context, c *Ctx) error {
	return stopPID(run(c, "code-server.pid"), syscall.SIGTERM, 10*time.Second)
}

func (s CodeServer) Status(c *Ctx) Status {
	return pidStatus(s, run(c, "code-server.pid"), fmt.Sprintf(":%d", c.Cfg.Code.Port))
}

func (CodeServer) Logs(c *Ctx) []string { return []string{logf(c, "code-server.log")} }

// Mirror runs `hampp mirror run`, a polling rsync from shared storage into the
// web root. inotify does not see writes other apps make on Android's FUSE
// storage, so it polls.
type Mirror struct {
	Self string // path of the hampp executable
}

func (Mirror) Name() string         { return "mirror" }
func (Mirror) Title() string        { return "mirror" }
func (Mirror) Packages() []string   { return []string{"rsync"} }
func (Mirror) Configure(*Ctx) error { return nil }

func (m Mirror) Start(_ context.Context, c *Ctx) error {
	pidFile := run(c, "mirror.pid")
	if proc.Running(pidFile) > 0 {
		return nil
	}
	if _, err := os.Stat(c.Cfg.Mirror.Source); err != nil {
		return fmt.Errorf("mirror source %s: %w (run termux-setup-storage and create the folder)", c.Cfg.Mirror.Source, err)
	}
	_, err := proc.Spawn(m.Self, []string{"mirror", "run"}, nil, logf(c, "mirror.log"), pidFile)
	return err
}

func (m Mirror) Stop(_ context.Context, c *Ctx) error {
	return stopPID(run(c, "mirror.pid"), syscall.SIGTERM, 5*time.Second)
}

func (m Mirror) Status(c *Ctx) Status {
	return pidStatus(m, run(c, "mirror.pid"), c.Paths.Short(c.Cfg.Mirror.Source))
}

func (Mirror) Logs(c *Ctx) []string { return []string{logf(c, "mirror.log")} }

// RsyncArgs builds the one-way mirror command. Dependency folders are excluded
// so npm/composer installs in the web root are never deleted by the mirror.
func RsyncArgs(src, dst string) []string {
	return []string{"-a", "--delete",
		"--exclude", "node_modules/", "--exclude", "vendor/", "--exclude", ".git/",
		"--no-perms", "--no-owner", "--no-group", "--omit-dir-times",
		trailingSlash(src), trailingSlash(dst)}
}

func trailingSlash(p string) string {
	if len(p) > 0 && p[len(p)-1] == '/' {
		return p
	}
	return p + "/"
}
