package config

import (
	"crypto/rand"
	"errors"
	"os"

	"github.com/pelletier/go-toml/v2"
)

// Credentials are generated secrets, stored 0600 next to config.toml.
type Credentials struct {
	DBRootPassword   string `toml:"db_root_password,omitempty"`
	DBUser           string `toml:"db_user,omitempty"`
	DBPassword       string `toml:"db_password,omitempty"`
	CodePassword     string `toml:"code_server_password,omitempty"`
	AdminerSQLitePwd string `toml:"adminer_sqlite_password,omitempty"`
}

func LoadCredentials(path string) (Credentials, error) {
	var c Credentials
	b, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return c, nil
	}
	if err != nil {
		return c, err
	}
	return c, toml.Unmarshal(b, &c)
}

func SaveCredentials(path string, c Credentials) error {
	b, err := toml.Marshal(c)
	if err != nil {
		return err
	}
	return WriteFileAtomic(path, append([]byte("# Generated by hampp. Keep private.\n"), b...), 0o600)
}

// NewPassword returns a random 128-bit password (base32) that is safe inside
// SQL, shell and TOML strings.
func NewPassword() string { return rand.Text() }
